# Databricks Apps runtime configuration
# Databricks Apps default to port 8000
# uv manages dependencies from pyproject.toml
command:
  - uv
  - run
  - dao-ai-builder

env:
  - name: STATIC_FOLDER
    value: static
  - name: PORT
    value: "8000"
  # DAO_AI_VERSION is now dynamically discovered from the installed package
  # GitHub repository for config templates
  - name: GITHUB_CONFIG_REPO
    value: "natefleming/dao-ai"
  - name: GITHUB_CONFIG_BRANCH
    value: "main"
  - name: GITHUB_CONFIG_PATH
    value: "config"

# Note: user_api_scopes are configured in databricks.yml, not here
# This file is for runtime configuration only
